-- MySQL Script generated by MySQL Workbench
-- 11/30/16 00:29:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema loyolastudentcenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loyolastudentcenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loyolastudentcenter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `loyolastudentcenter` ;

-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`migration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`migration` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`migration` (
  `version` VARCHAR(180) NOT NULL COMMENT '',
  `apply_time` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`version`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`user` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `status` SMALLINT(6) NOT NULL DEFAULT '10' COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  `lastname` VARCHAR(100) NOT NULL COMMENT '',
  `firstname` VARCHAR(100) NOT NULL COMMENT '',
  `middlename` VARCHAR(100) NULL DEFAULT '-' COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `gender` ENUM('Male', 'Female') NOT NULL COMMENT '',
  `contact_number` VARCHAR(12) NULL COMMENT '',
  `home_address` VARCHAR(200) NOT NULL COMMENT '',
  `school` VARCHAR(200) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(100) NOT NULL COMMENT '',
  `relation` ENUM('Parent', 'Grandparent', 'Sibling', 'Other') NOT NULL COMMENT '',
  `guardian_contact_number` VARCHAR(12) NOT NULL COMMENT '',
  `guardian_email_address` VARCHAR(150) NULL COMMENT '',
  `learned_lsc` ENUM('friends', 'relatives', 'newspaper ads', 'LSC signage/poster', 'school', 'others') NOT NULL COMMENT '',
  `date` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`review_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`review_class` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`review_class` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(150) NOT NULL COMMENT '',
  `description` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`admin` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `status` SMALLINT(6) NOT NULL DEFAULT '10' COMMENT '',
  `created_at` INT(11) NOT NULL COMMENT '',
  `updated_at` INT(11) NOT NULL COMMENT '',
  `lastname` VARCHAR(100) NOT NULL COMMENT '',
  `firstname` VARCHAR(100) NOT NULL COMMENT '',
  `middlename` VARCHAR(100) NULL DEFAULT '-' COMMENT '',
  `contact_number` VARCHAR(12) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `email` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`schedule` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `review_class_id` INT NOT NULL COMMENT '',
  `batch` VARCHAR(100) NOT NULL COMMENT '',
  `duration_of_hours` INT(3) NOT NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  `start_time` TIME NULL COMMENT '',
  `end_time` TIME NULL COMMENT '',
  `days` VARCHAR(250) NULL COMMENT '',
  `location` VARCHAR(150) NOT NULL COMMENT '',
  `room` VARCHAR(150) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_schedule_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_schedule_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`transaction` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`transaction` (
  `user_id` INT(11) NOT NULL COMMENT '',
  `review_class_id` INT NOT NULL COMMENT '',
  `schedule_id` INT NOT NULL COMMENT '',
  `transaction_type` ENUM('Reserve', 'Enroll') NOT NULL COMMENT '',
  `selected_school` VARCHAR(100) NOT NULL COMMENT '',
  `status` ENUM('Pending', 'Reserved', 'Enrolled', 'Done', 'Cancelled') NOT NULL DEFAULT 'Pending' COMMENT '',
  `date` TIMESTAMP NOT NULL COMMENT '',
  INDEX `fk_user_has_review_class_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  INDEX `fk_user_has_review_class_user_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_transaction_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  CONSTRAINT `fk_user_has_review_class_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `loyolastudentcenter`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_review_class_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `loyolastudentcenter`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`payment` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `payment_slip` VARCHAR(250) NULL COMMENT '',
  `date` TIMESTAMP NOT NULL COMMENT '',
  `transaction_user_id` INT(11) NOT NULL COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_payment_transaction1_idx` (`transaction_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_payment_transaction1`
    FOREIGN KEY (`transaction_user_id`)
    REFERENCES `loyolastudentcenter`.`transaction` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`class_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loyolastudentcenter`.`class_list` ;

CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`class_list` (
  `review_class_id` INT NOT NULL COMMENT '',
  `user_id` INT(11) NOT NULL COMMENT '',
  INDEX `fk_review_class_has_user_user1_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_review_class_has_user_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_class_has_user_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_class_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `loyolastudentcenter`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
