-- MySQL Script generated by MySQL Workbench
-- 10/27/16 15:39:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema loyolastudentcenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loyolastudentcenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loyolastudentcenter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `loyolastudentcenter` ;

-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`review_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`review_class` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(150) NOT NULL COMMENT '',
  `description` VARCHAR(400) NOT NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `review_class_id` INT NOT NULL COMMENT '',
  `duration_of_hours` INT(3) NULL COMMENT '',
  `start_time` TIME NULL COMMENT '',
  `end_time` TIME NULL COMMENT '',
  `location` VARCHAR(150) NULL COMMENT '',
  `room` VARCHAR(150) NULL COMMENT '',
  PRIMARY KEY (`id`, `review_class_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_schedule_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_schedule_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lastname` VARCHAR(100) NOT NULL COMMENT '',
  `firstname` VARCHAR(100) NOT NULL COMMENT '',
  `middlename` VARCHAR(100) NULL DEFAULT '-' COMMENT '',
  `age` INT(2) NOT NULL COMMENT '',
  `gender` ENUM('Male', 'Female') NOT NULL COMMENT '',
  `contact_number` VARCHAR(12) NULL COMMENT '',
  `email_address` VARCHAR(150) NOT NULL COMMENT '',
  `home_address` VARCHAR(200) NOT NULL COMMENT '',
  `school` VARCHAR(200) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(100) NOT NULL COMMENT '',
  `relation` ENUM('Parent', 'Grandparent', 'Sibling', 'Other') NOT NULL COMMENT '',
  `guardian_contact_number` VARCHAR(12) NOT NULL COMMENT '',
  `guardian_email_address` VARCHAR(150) NULL COMMENT '',
  `selected_school` VARCHAR(100) NULL COMMENT '',
  `learned_lsc` ENUM('friends', 'relatives', 'newspaper ads', 'LSC signage/poster', 'school', 'others') NOT NULL COMMENT '',
  `review_class_id` INT NOT NULL COMMENT '',
  `schedule_id` INT NOT NULL COMMENT '',
  `transaction_type` ENUM('Reserve', 'Enroll') NOT NULL DEFAULT 'Reserve' COMMENT '',
  `date_of_registration` TIMESTAMP NOT NULL COMMENT '',
  `status` ENUM('Pending', 'Reserved', 'Enrolled', 'Done', 'Cancelled') NULL DEFAULT 'Pending' COMMENT '',
  PRIMARY KEY (`id`, `review_class_id`, `schedule_id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_student_schedule1_idx` (`schedule_id` ASC)  COMMENT '',
  INDEX `fk_student_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_student_schedule1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `loyolastudentcenter`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`account` (
  `id` INT NOT NULL COMMENT '',
  `username` VARCHAR(50) NOT NULL COMMENT '',
  `email_address` VARCHAR(150) NOT NULL COMMENT '',
  `password` VARCHAR(50) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `student_id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `password_UNIQUE` (`password` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  INDEX `fk_account_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_account_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `loyolastudentcenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`class_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`class_list` (
  `review_class_id` INT NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`review_class_id`, `student_id`)  COMMENT '',
  INDEX `fk_student_has_review_class_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  INDEX `fk_student_has_review_class_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_student_has_review_class_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `loyolastudentcenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_review_class_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'bridge entity';


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`payment` (
  `student_id` INT NOT NULL COMMENT '',
  `review_class_id` INT NOT NULL COMMENT '',
  `deposit_slip` VARCHAR(250) NULL COMMENT '',
  `date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`student_id`, `review_class_id`)  COMMENT '',
  INDEX `fk_review_class_has_student_student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_review_class_has_student_review_class1_idx` (`review_class_id` ASC)  COMMENT '',
  CONSTRAINT `fk_review_class_has_student_review_class1`
    FOREIGN KEY (`review_class_id`)
    REFERENCES `loyolastudentcenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_class_has_student_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `loyolastudentcenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loyolastudentcenter`.`contact_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loyolastudentcenter`.`contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sender_name` VARCHAR(50) NOT NULL COMMENT '',
  `sender_email` VARCHAR(200) NOT NULL COMMENT '',
  `subject` VARCHAR(200) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
