-- MySQL Script generated by MySQL Workbench
-- 08/15/16 19:25:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lscenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lscenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lscenter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lscenter` ;

-- -----------------------------------------------------
-- Table `lscenter`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `number_of_hours` INT NULL COMMENT '',
  `review_class` VARCHAR(45) NOT NULL COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `nickname` VARCHAR(15) NOT NULL COMMENT '',
  `gender` VARCHAR(7) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(45) NOT NULL COMMENT '',
  `contact_number` INT NOT NULL COMMENT '',
  `address` VARCHAR(45) NOT NULL COMMENT '',
  `school` VARCHAR(45) NOT NULL COMMENT '',
  `school_address` VARCHAR(50) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(40) NULL COMMENT '',
  `relation` VARCHAR(45) NULL COMMENT '',
  `guardian_contact_number` INT NULL COMMENT '',
  `guardian_email_address` VARCHAR(45) NULL COMMENT '',
  `date_of_registration` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `Students_ID_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  UNIQUE INDEX `contact_number_UNIQUE` (`contact_number` ASC)  COMMENT ''
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`Instructor_has_Manangement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`Instructor_has_Manangement` (
  `Instructor_idInstructor` INT NOT NULL COMMENT '',
  `Instructor_Clerk_idClerk` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Instructor_idInstructor`, `Instructor_Clerk_idClerk`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`Students_has_Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`Students_has_Subject` (
  `Students_Stud_ID` INT NOT NULL COMMENT '',
  `Subject_Subject_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Students_Stud_ID`, `Subject_Subject_ID`)  COMMENT '',
  INDEX `fk_Students_has_Subject_Students1_idx` (`Students_Stud_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_has_Subject_Students1`
    FOREIGN KEY (`Students_Stud_ID`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`review_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`review_class` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(30) NOT NULL COMMENT '',
  `description` TEXT(200) NOT NULL COMMENT '',
  `schedule` VARCHAR(150) NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idSubject_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `gender` VARCHAR(10) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `contact_Number` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idInstructor_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  UNIQUE INDEX `contact_Number_UNIQUE` (`contact_Number` ASC)  COMMENT ''
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`enrollment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `schedule` VARCHAR(100) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `ID_Enrollment_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_Enrollment_Employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_enrollment_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Enrollment_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lscenter`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enrollment_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `reciept_number` VARCHAR(45) NOT NULL COMMENT '',
  `amount` INT NOT NULL COMMENT '',
  `balance` INT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `reciept_number_UNIQUE` (`reciept_number` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_payment_student1_idx` (`student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_payment_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `schedule` VARCHAR(100) NOT NULL COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_Reservation_Student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_Employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lscenter`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`class_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`class_list` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `student_id` INT NOT NULL COMMENT '',
  `review_Class_id` INT NOT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  `atendance` VARCHAR(100) NULL COMMENT '',
  `missed_class` VARCHAR(100) NULL COMMENT '',
  `date` DATE NULL COMMENT '',
  INDEX `fk_Student_has_Review_Class_Review_Class1_idx` (`review_Class_id` ASC)  COMMENT '',
  INDEX `fk_Class List_Student1_idx` (`student_id` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_class_list_employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_has_Review_Class_Review_Class1`
    FOREIGN KEY (`review_Class_id`)
    REFERENCES `lscenter`.`review_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class List_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_list_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lscenter`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lscenter`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lscenter`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email_address` VARCHAR(45) NOT NULL COMMENT '',
  `user_name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `student_id` INT NULL COMMENT '',
  `employee_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  INDEX `fk_account_student1_idx` (`student_id` ASC)  COMMENT '',
  INDEX `fk_account_employee1_idx` (`employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_account_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `lscenter`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `lscenter`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
