-- MySQL Script generated by MySQL Workbench
-- 08/06/16 21:53:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email_address` VARCHAR(45) NOT NULL COMMENT '',
  `user_name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `number_of_hours` INT NULL COMMENT '',
  `review_class` VARCHAR(45) NOT NULL COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `nickname` VARCHAR(15) NOT NULL COMMENT '',
  `gender` VARCHAR(7) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(45) NOT NULL COMMENT '',
  `contact_number` INT NOT NULL COMMENT '',
  `address` VARCHAR(45) NOT NULL COMMENT '',
  `school` VARCHAR(45) NOT NULL COMMENT '',
  `school_address` VARCHAR(50) NOT NULL COMMENT '',
  `guardian_name` VARCHAR(40) NULL COMMENT '',
  `relation` VARCHAR(45) NULL COMMENT '',
  `guardian_contact_number` INT NULL COMMENT '',
  `guardian_email_address` VARCHAR(45) NULL COMMENT '',
  `date_of_registration` DATE NOT NULL COMMENT '',
  `Employee_id` INT NULL COMMENT '',
  `Account_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `Students_ID_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  UNIQUE INDEX `contact_number_UNIQUE` (`contact_number` ASC)  COMMENT '',
  INDEX `fk_Student_Account1_idx` (`Account_id` ASC)  COMMENT '',
  UNIQUE INDEX `Account_id_UNIQUE` (`Account_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructor_has_Manangement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructor_has_Manangement` (
  `Instructor_idInstructor` INT NOT NULL COMMENT '',
  `Instructor_Clerk_idClerk` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Instructor_idInstructor`, `Instructor_Clerk_idClerk`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students_has_Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students_has_Subject` (
  `Students_Stud_ID` INT NOT NULL COMMENT '',
  `Subject_Subject_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Students_Stud_ID`, `Subject_Subject_ID`)  COMMENT '',
  INDEX `fk_Students_has_Subject_Students1_idx` (`Students_Stud_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_Students_has_Subject_Students1`
    FOREIGN KEY (`Students_Stud_ID`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review_Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review_Class` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(30) NOT NULL COMMENT '',
  `description` TEXT(200) NOT NULL COMMENT '',
  `schedule` VARCHAR(150) NULL COMMENT '',
  `start_date` DATE NULL COMMENT '',
  `end_date` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idSubject_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lastname` VARCHAR(30) NOT NULL COMMENT '',
  `firstname` VARCHAR(30) NOT NULL COMMENT '',
  `middlename` VARCHAR(30) NULL COMMENT '',
  `gender` VARCHAR(10) NOT NULL COMMENT '',
  `age` INT NOT NULL COMMENT '',
  `contact_Number` INT NOT NULL COMMENT '',
  `email_address` VARCHAR(30) NOT NULL COMMENT '',
  `Account_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idInstructor_UNIQUE` (`id` ASC)  COMMENT '',
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC)  COMMENT '',
  UNIQUE INDEX `contact_Number_UNIQUE` (`contact_Number` ASC)  COMMENT '',
  INDEX `fk_Employee_Account1_idx` (`Account_id` ASC)  COMMENT '',
  UNIQUE INDEX `Account_id_UNIQUE` (`Account_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Employee_Account1`
    FOREIGN KEY (`Account_id`)
    REFERENCES `mydb`.`Account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `schedule` VARCHAR(100) NOT NULL COMMENT '',
  `Employee_id` INT NULL COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `ID_Enrollment_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_Enrollment_Employee1_idx` (`Employee_id` ASC)  COMMENT '',
  INDEX `fk_Enrollment_Student1_idx` (`Student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Enrollment_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollment_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `reciept_number` VARCHAR(45) NOT NULL COMMENT '',
  `amount` INT NOT NULL COMMENT '',
  `balance` INT NULL COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `reciept_number_UNIQUE` (`reciept_number` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_Payment_Student1_idx` (`Student_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Payment_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `schedule` VARCHAR(100) NOT NULL COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Employee_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_Reservation_Student1_idx` (`Student_id` ASC)  COMMENT '',
  INDEX `fk_Reservation_Employee1_idx` (`Employee_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Reservation_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `mydb`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class List` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Student_id` INT NOT NULL COMMENT '',
  `Review_Class_id` INT NOT NULL COMMENT '',
  `Employee_id` INT NOT NULL COMMENT '',
  `Attendance` VARCHAR(100) NULL COMMENT '',
  `missed_class` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Student_has_Review_Class_Review_Class1_idx` (`Review_Class_id` ASC)  COMMENT '',
  INDEX `fk_Class List_Student1_idx` (`Student_id` ASC, `Employee_id` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  CONSTRAINT `fk_Student_has_Review_Class_Review_Class1`
    FOREIGN KEY (`Review_Class_id`)
    REFERENCES `mydb`.`Review_Class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class List_Student1`
    FOREIGN KEY (`Student_id` , `Employee_id`)
    REFERENCES `mydb`.`Student` (`id` , `Employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
